forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-apt', '< 9.0.0'
mod 'puppetlabs-stdlib', '< 7.0.0'
mod 'puppetlabs-inifile'
mod 'puppetlabs-ntp'
mod 'puppet-unattended_upgrades'
mod 'mmckinst-hash2stuff'
mod 'puppetlabs-vcsrepo'
mod 'puppetlabs-lvm'
mod 'saz/sudo'
mod 'saz/timezone'
mod 'ghoneycutt-ssh', '< 4.0.0'
mod 'puppet-archive'
mod 'kemra102-snapd'

mod 'brwyatt/syncthing', git: 'https://github.com/jovandeginste/puppet-syncthing.git'
mod 'coderdojorotselaar/profile', git: 'https://github.com/CoderDojoRotselaar/os-profile.git'
