forge 'https://forgeapi.puppetlabs.com'

mod 'puppetlabs-apt'
mod 'puppetlabs-stdlib'
mod 'puppetlabs-inifile'
mod 'puppetlabs-ntp'
mod 'puppet-unattended_upgrades'
mod 'mmckinst-hash2stuff'
mod 'puppetlabs-vcsrepo'
mod 'puppetlabs-lvm', git: 'https://github.com/puppetlabs/puppetlabs-lvm.git'
mod 'saz/sudo'
mod 'saz/timezone'
mod 'ghoneycutt-ssh'
mod 'puppet-archive'
mod 'kemra102-snapd'

mod 'brwyatt/syncthing', git: 'https://github.com/jovandeginste/puppet-syncthing.git'
mod 'coderdojorotselaar/profile', git: 'https://github.com/CoderDojoRotselaar/os-profile.git'
